name: comeback
description: "A religious Flutter app for prayer requests, gospel media, chat and spiritual support."
publish_to: 'none' # Remove to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase core services
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

  # Optional: Add these for better state management, animations, or UI improvements
  provider: ^6.1.2 # For state management, if needed
  flutter_spinkit: ^5.2.0 # For nice loading animations
  google_fonts: ^6.2.0 # If you want custom fonts from Google

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true

  assets:
    #- assets/images/
    #- assets/videos/
    #- assets/audio/
    #- assets/json/

  # Example fonts section, if you plan to use custom fonts:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
